Feedback
PUM-05/frontend pull request #53
Opened 2023-04-26 08:42 UTC by Lindstrong

2023-04-26 09:43 UTC, Lindstrong commented
> Typ feedback när man inte har fyllt i något fält eller och klickar på skicka? Ni får gärna specificera vad ni menar med error.

2023-04-26 09:59 UTC, Snoffla commented
> Typ feedback när man inte har fyllt i något fält eller och klickar på skicka? Ni får gärna specificera vad ni menar med error.

Min första tanke var om skapandet misslyckas, dvs ej status 201 i detta fall.

2023-04-26 10:55 UTC, Lindstrong commented
> > Typ feedback när man inte har fyllt i något fält eller och klickar på skicka? Ni får gärna specificera vad ni menar med error.
> 
> Min första tanke var om skapandet misslyckas, dvs ej status 201 i detta fall.

Är det inte uppenbart i det fallet att det är misslyckat om du inte får ett bekräftat lyckat meddelande?

2023-05-12 08:02 UTC, PontusFerm approved these changes
Nu verkar det fungera, snyggt!

Jag såg dock att det låg en del console.logs() kvar i koden lite här och var, så det ser ut såhär i console. Vore nice om de togs bort innan den här mergeas in i main .

![image](https://github.com/PUM-05/frontend/assets/123727457/0e15fcde-62dd-4529-a9ee-5999e7611a32)

2023-05-12 11:21 UTC, Snoffla requested changes
Bra jobbat 😀. Får dock inget felmeddelande när informationen är rätt ifylld men servern misslyckas. Kan vara bra att visa att ärendet inte sparats.

2023-05-12 11:53 UTC, Snoffla approved these changes

2023-05-15 06:14 UTC, merged